### ISSUE TITLE
Schedule scripts won't update event-specific YAML files

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2023#23]
The issue is discovered after updating the [schedule worksheet 2023](https://docs.google.com/spreadsheets/d/1tGtGffcbCRxQFjE3ej42IcWlN4FJCsuQeZvETt9g0oA/edit#gid=1567094615). The title "Tidy genomic and transcriptomic analyses" was updated to "Tidy genomic and transcriptomic single-cell analyses". After running `Rscript --vanilla 1_create_yaml.R; bash 2_create_abstracts.sh; bash 3_create_tracks.sh`, the schedule reflects the change. But the [event-specific page](https://bioc2023.bioconductor.org/abstracts/paper3/) was not updated. It was fixed manually in  https://github.com/Bioconductor/BioC2023/commit/c7ff16aadc2bc85f78762ed22ed4c04f17e16c5e, but needs to be investigated.

**Comment by mdozmorov** [comment]
It was also noted that some authors for keynotes are not in the schedule despite being in the spreadsheet. The authors are listed for the first two keynotes but not the others. Something major is not working in the schedule scripts. Example:
<img width="1302" alt="image" src="https://github.com/Bioconductor/BioC2023/assets/864945/e75346ef-7651-46c9-ad43-d1ecd51f9fd0">
![image](https://github.com/Bioconductor/BioC2023/assets/864945/974e7723-20d8-4f14-8b3e-5bc7e69103ea)

**Comment by mdozmorov** [comment]
Or, the problem is in the HUGO code somewhere. The YAML files for keynotes have the "authors" fields, but they are not rendered.

**Comment by mdozmorov** [comment]
Manually adding the authors to the 'presenting author' field helped, but it needs to be automated.

**Comment by sdgamboa** [comment]
For the keynote titles and text in general there is a problem with the quotation marks ' and ". 
This is because the fields in the YAML use " to delimit the field. I have some code that changes " to '. So only double quotations should be used in the spreadsheets ".

**Comment by mdozmorov** [comment]
Most of the keynotes don't use either quotation marks. It seems something is wrong with 'authors' and 'presenting_author' fields because populating the latter manually solved the problem. Automatic processing of those fields doesn't work.

**Comment by sdgamboa** [comment]
Yes. Only presenting authors are displayed.

**Comment by sdgamboa** [comment]
@mdozmorov, there was a column named authors that was removed. Apparently on July 7 according to the spreadsheet history. The column authors and the columns presenting_authors* serve two different purposes. The 1_create_yaml script didn't work because it was trying to get the column authors for creating the abstract pages. @mdozmorov, could you restore the column and see if this solves the problem?

**Comment by sdgamboa** [comment]
@mdozmorov, I also see two columns named github, which I'm not sure if it will create another type of error, preventing the yamls to be created.

**Comment by mdozmorov** [comment]
Yes, this happened by accident. Restoring the 'authors' column appears to fix everything. I also removed the extra 'github' column. Thanks, @sdgamboa!

**Comment by sdgamboa** [comment]
@mdozmorov, all right. Actually, quotation should be single (') in the text in the spreadsheet. My bad. I updated the Keynote with single quotes in this PR #20

**Comment by mdozmorov** [comment]
Great! And I'll add the note about quotes to the README instructions.
