### ISSUE TITLE
rename master branch to devel

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BioC2023#8]
Hi organizers,

Perhaps Mikhail @mdozmorov or someone can change the default branch name to align with Bioconductor's code of conduct. 
See here for more information: http://contributions.bioconductor.org/branch-rename-faqs.html
I can also take care of this, if you'd like. 

Best regards,
Marcel

**Comment by mdozmorov** [comment]
I could create the branch but don't have permissions to change the settings. Marcel, if you can look into it, that'll be great. I will reconfigure Netlify to pull from that branch.

**Comment by LiNk-NY** [comment]
Thanks Mikhail! @mdozmorov 
I have changed the default branch to `devel` and removed the `master` branch. 

Note. I didn't see any configurations in the repo that mention `master`.

**Comment by mdozmorov** [comment]
It's the setting on the Netlify's side. Fixed, now works with the devel branch.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/864945/225491123-73e18436-3ce1-43a6-88ec-62ca552ba99b.png">
